name: CI/CD

on:
  push:

jobs:
  cancel-previous-builds:
    name: Cancel Previous Build Runs
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 30
    steps:
      - name: Cancel Previous Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  add_jira_fix_version:
    name: Add Jira Fix Version to Jira ticket
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Source Branch Name
        id: get_source_branch_name
        run: |
          # # Get the Source Branch Name from commit merge message
          # MERGE_COMMIT_MESSAGE=$(git log --format=%B -n 1 "${GITHUB_SHA}")
          # SOURCE_BRANCH_NAME=$(echo "$MERGE_COMMIT_MESSAGE" | grep -oP '(?<=from ).*' | awk -F/ '{print $NF}')
          # echo "Souce Branch Name: $SOURCE_BRANCH_NAME"
          echo "SOURCE_BRANCH_NAME=no-ticket-in-this-branch" >> $GITHUB_ENV
      - name: Get Jira Ticket Number
        id: get_jira_ticket_number
        # run only if the source branch name startswith bc- or BC-
        # use startWith from github actions
        if: startsWith(env.SOURCE_BRANCH_NAME, 'bc-') || startsWith(env.SOURCE_BRANCH_NAME, 'BC-')
        # get the jira ticket number from the prefix of the branch name,
        # for example "BC-12345-this is my brach-name" will be jira ticket BC-12345
        run: |
          echo "get the jira ticket number from the prefix of the branch name"
          echo "for example 'BC-12345-this is my brach-name' will be jira ticket BC-12345"
          JIRA_TICKET_NUMBER=$(echo ${{ env.SOURCE_BRANCH_NAME }} | grep -oP '([A-Z]+-\d+)' > 
          echo "Jira ticket number: $JIRA_TICKET_NUMBER"
          # Set the output variable
          echo "JIRA_TICKET_NUMBER=$JIRA_TICKET_NUMBER" >> $GITHUB_ENV
      - name: Add Fix Version to Jira Ticket
        if: env.JIRA_TICKET_NUMBER != 'NO-TICKET-FOUND'
        run: |
          echo "TICKET NUMBER: ${{ env.JIRA_TICKET_NUMBER }}"

          