name: CI/CD

on:
  push:
  #   branches:
  #     - develop
  #     - rc
  #     - hotfix
  #     - main

  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize

jobs:
  cancel-previous-builds:
    name: Cancel Previous Build Runs
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 30
    steps:
      - name: Cancel Previous Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  add_jira_fix_version:
    name: Add Jira Fix Version to Jira ticket
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # get the jira ticket number from the prefix of the branch name or pull request title, 
      # for example "BC-12345-this is my brach-name" will be jira ticket BC-12345
      - name: Get Jira Ticket Number
        id: get_jira_ticket_number
        run: |
          echo "get the jira ticket number from the prefix of the branch name or pull request title"
          echo "for example 'BC-12345-this is my brach-name' will be jira ticket BC-12345"
          echo "Branch name ref: ${{ github.ref_name }}"
          echo "Branch name base: ${{ github.event.pull_request.base.ref }}"
          JIRA_TICKET_NUMBER=$(echo ${{ github.event.pull_request.base.ref }} | grep -oP '([A-Z]+-\d+)')
          if [ -z "$JIRA_TICKET_NUMBER" ]; then
            echo "No ticket number found in branch name, checking pull request title..."
            JIRA_TICKET_NUMBER=$(echo ${{ github.event.pull_request.title }} | grep -oP '([A-Z]+-\d+)')
          fi
          echo "Jira ticket number: $JIRA_TICKET_NUMBER"
          # Set the output variable
          echo "JIRA_TICKET_NUMBER=$JIRA_TICKET_NUMBER" >> $GITHUB_ENV