name: CI/CD

on:
  push:
  #   branches:
  #     - develop
  #     - rc
  #     - hotfix
  #     - main

  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize

jobs:
  cancel-previous-builds:
    name: Cancel Previous Build Runs
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 30
    steps:
      - name: Cancel Previous Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  add_jira_fix_version:
    name: Add Jira Fix Version to Jira ticket
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Source Branch Name
        id: get_branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Print Source Branch Name
        run: echo "Source branch name is ${{ env.BRANCH_NAME }}"